.gitignore, README.md
- [docs: 개인 개발 전략 기재](https://github.com/bside-tinkerbell/Waving-iOS/commit/ba1d85987db97551c1b6a8dea04034d0f544606a)
- [chore: gitignore 에 의미없는 파일 추가](https://github.com/bside-tinkerbell/Waving-iOS/commit/1c848b30d538f4639edd49bc71dea3d904f4b195)
=> README.md 수정 및 gitignore 파일 수정 

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Application/SceneDelegate.swift, Waving-iOS/DesignSystem/Font/FontManager.swift, Waving-iOS/Info.plist, Waving-iOS/Presentation/Common/WVButton.swift, Waving-iOS/Presentation/Signup/ViewController/IntroViewController.swift
- Font 파일 경로 변경
- Info.plist 에 Font 정보 추가
- Pretendard font 사용을 위한 UIFont extension 구현
- intro 화면 > route 로직 수정
=> Font 경로 변경, Intro 화면 route 로직 수정

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/DesignSystem/Components/NavigationBar/NavigationView.swift, Waving-iOS/Presentation/Etc/ViewController.swift, Waving-iOS/Presentation/Friends/View/FriendsIntroView.swift, Waving-iOS/Presentation/Friends/View/FriendsListView.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift, Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift
#29 #30 
- 지인 불러오기 화면 UI 구성
- Contacts 프레임 워크를 활용한 연락처 호출 로직 추가
=> [Feat] 지인 추가 Intro 화면 UI 구성 + Contacts 프레임워크 연결

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Data/Network/Friends/FriendsAPI.swift, Waving-iOS/Data/Network/Friends/FriendsTarget.swift, Waving-iOS/Data/Network/URLString.swift, Waving-iOS/Domain/Friends/FriendsModel.swift, Waving-iOS/Domain/Friends/SaveFriendsModel.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift
=> [Feat] 지인 추가를 위한 API 설계

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Data/Network/Greeting/GreetingAPI.swift, Waving-iOS/Data/Network/Greeting/GreetingTarget.swift, Waving-iOS/Domain/GreetingModel.swift, Waving-iOS/Presentation/MainTabBar/ViewController/HomeViewController.swift, Waving-iOS/Presentation/MainTabBar/ViewModel/HomeViewModel.swift
- 홈화면 랜덤 인삿말 > 서버에서 가져오도록 수정했습니다 :)
=> feat: 홈화면 랜덤 인삿말 로직 구현

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Common/ClipboardManager.swift, Waving-iOS/Presentation/MainTabBar/View/GreetingSuggestionCollectionViewCell.swift, Waving-iOS/Presentation/MainTabBar/ViewModel/GreetingSuggestionCellModel.swift
- 추천 인삿말 셀 구현
- 클립보드에 복사 액션 구현 (ClipboardManager.swift)
=> [Feat] 메인 화면 구현 > 추천 인삿말 셀 구현

Waving-iOS/Data/Network/Greeting/GreetingAPI.swift, Waving-iOS/Data/Network/Greeting/GreetingTarget.swift, Waving-iOS/Domain/Entity/Greeting/GreetingModel.swift, Waving-iOS/Presentation/Common/TabView/TopTabBarViewController.swift, Waving-iOS/Presentation/MainTabBar/ViewController/HomeViewController.swift
- 홈 화면에서 인사말 카테고리 화면으로 진입하기 전 카테고리 조회
=> [Feat] 인사말 카테고리 화면으로 진입하기 전 카테고리 조회

Waving-iOS/Data/API/APIClient.swift, Waving-iOS/Data/API/APIEndpoint.swift, Waving-iOS/Presentation/Friends/View/FriendsContactCollectionViewCell.swift, Waving-iOS/Presentation/Friends/View/FriendsListView.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift, Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift, Waving-iOS/Presentation/Sample/SampleViewModel.swift
- 지인 리스트 UI 구성( 즐겨 찾는 지인 없는 버전)
- 지인 관련 API FriendsViewModel로 옮김
=> [Feat] 지인리스트 관련

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Application/SceneDelegate.swift, Waving-iOS/Data/Network/Greeting/GreetingTarget.swift, Waving-iOS/Data/Network/Sign/SignAPI.swift, Waving-iOS/Data/Network/Sign/SignTarget.swift, Waving-iOS/Domain/Entity/SIgn/AuthCodeModel.swift, Waving-iOS/Domain/Entity/SIgn/SignRequestModel.swift, Waving-iOS/Presentation/Common/Toast/Toast.swift, Waving-iOS/Presentation/Signup/View/SignupStepPhoneNumberView.swift, Waving-iOS/Presentation/Signup/ViewModel/IntroViewModel.swift, Waving-iOS/Presentation/Signup/ViewModel/SignupStepViewModel.swift
- 회원가입에 필요한 API 추가
- 폰번호 포맷팅 메서드 추가
=> [Feat] 회원가입

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Data/Network/Sign/SignAPI.swift, Waving-iOS/Domain/Entity/SIgn/SignUpResponseModel.swift
=> feat: 앱에서 가입 안되는 이슈 해결

Waving-iOS/Data/API/Friends/FriendsEndpoint.swift
- 임의적으로 16으로 sample로 들어 있던 user_id를 로그인 후 받아온 id로 바꿈 (LoginDataStore.shared.userId)
=> [Feat] user_id 변경

Waving-iOS/Data/API/Friends/FriendsEndpoint.swift, Waving-iOS/Data/DTO/Friends/GetFriendsDTO.swift, Waving-iOS/Data/DTO/Friends/SaveFriendsDTO.swift, Waving-iOS/Domain/Entity/Friends/ContactEntity.swift, Waving-iOS/Domain/Entity/Friends/GetFriendsEntity.swift, Waving-iOS/Info.plist, Waving-iOS/Presentation/Friends/View/FriendsAddView.swift, Waving-iOS/Presentation/Friends/View/FriendsContactCollectionViewCell.swift, Waving-iOS/Presentation/Friends/View/FriendsDisconnectView.swift, Waving-iOS/Presentation/Friends/View/FriendsIntroView.swift, Waving-iOS/Presentation/Friends/View/FriendsListView.swift, Waving-iOS/Presentation/Friends/ViewController/FriendsContactViewController.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsContactViewModel.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift, Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift
더 이상 테스트용이 아닌 로그인 후 받아 온 user_id 통해 아래와 같은 기능들을 구현하도록 수정하였습니다.
재은님 우리 이제 그래도 거의 다 온 거 같아요. 화이팅! ❤️
=> [Feat] 지인 추가,  지인 리스트 실제 아이디로 동작하도록 수정

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift
=> [Fix] 1.0.0 리젝에 대한 오류 해결

Waving-iOS/Presentation/Common/NavigationBar/HomeNavigationView.swift, Waving-iOS/Presentation/Main/View/GreetingTableViewCell.swift
- 안쓰는 버튼 (인사말 공유, 즐겨찾기, 홈 네비게이션 알림 버튼) 을 숨겼습니다
=> [Fix] 1.0.0 심사 리젝 대응

Waving-iOS/Data/Network/Greeting/GreetingAPI.swift, Waving-iOS/Data/Network/Greeting/GreetingTarget.swift, Waving-iOS/Domain/Entity/Greeting/GreetingModel.swift, Waving-iOS/Presentation/Common/TabView/TopTabBarViewController.swift, Waving-iOS/Presentation/Main/ViewController/GreetingListViewController.swift, Waving-iOS/Presentation/Main/ViewModel/GreetingCellModel.swift, Waving-iOS/Presentation/MainTabBar/ViewController/HomeViewController.swift, Waving-iOS/Presentation/MainTabBar/ViewModel/GreetingCategoryCellModel.swift, Waving-iOS/Presentation/MainTabBar/ViewModel/HomeViewModel.swift
- 홈 > 인사말 카테고리 목록 서버에서 조회해서 노출하도록,
- 인사말 카테고리마다 API 호출하도록 수정했습니다.
=> feat: 인사말 리스트 화면 수정

Waving-iOS/Presentation/Friends/ViewController/FriendsContactViewController.swift, Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift, Waving-iOS/Presentation/MainTabBar/ViewController/SettingViewController.swift, Waving-iOS/Presentation/Signup/ViewController/LoginViewController.swift
- 다크모드 대응 안되어 있어서 light 모드 강제화 함
- 주석 제거
=> 다크모드 대응 안되어 있어서 light 모드 강제화 함

Waving-iOS.xcodeproj/project.pbxproj, Waving-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Waving-iOS/Common/PhoneNumberManager.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift
나의 지인 화면에서 이름 탭했을 때 동작 안 하는 버그를 해결하기 위해 시도했는데 실패했어요 ㅎㅎ
폰 넘버 형식을 서버와 맞춰야 해결할 수 있을 것 같아요.
#85 를 참고해주세요 :)
=> 나의 지인 화면에서 이름 탭했을 때 동작 안 하는 버그

Waving-iOS/Presentation/MainTabBar/View/GreetingSuggestionCollectionViewCell.swift
- 앱 심사 결과 고치려다가 테스트 코드 제거
<br/>
- 로그인, 가입 버튼이 비활성화된다는 버그는 재현을 못했네요
<br/>
=> [CHORE] 테스트 코드 제거

Waving-iOS/Presentation/Signup/ViewController/LoginViewController.swift, Waving-iOS/Presentation/Signup/ViewModel/LoginViewModel.swift
- 로그인 버튼 활성화 안되는 버그 수정
- debounce, throttle, dropFirst operator 제거 (이메일을 타이핑하지 않고 복붙했을때 버튼 활성화 안됨)
=> [FIX] 심사 피드백 적용: 로그인 안되는 이슈

Waving-iOS/Data/API/APIClient.swift, Waving-iOS/Data/API/APIEndpoint.swift, Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift, Waving-iOS/Presentation/Signup/ViewController/LoginViewController.swift
해당 없음
<br/>
- 로그인 버튼 라벨 변경
- 네트워크 관련 코드 수정
<br/>
=> [REFACTOR] 코드 수정

Waving-iOS/Presentation/Signup/View/SignupStepPhoneNumberView.swift, Waving-iOS/Presentation/Signup/View/SignupStepTermOfUseView.swift, Waving-iOS/Presentation/Signup/View/SignupStepUsernameView.swift, Waving-iOS/Presentation/Signup/ViewController/SignupViewController.swift, Waving-iOS/Presentation/Signup/ViewModel/SignupStepViewModel.swift, Waving-iOSTests/Waving_iOSTests.swift
#108 
- 가입 시 다음 버튼, 인증번호, 인증번호 확인 버튼 활성화 로직 추가 및 고도화
- 이름, 폰번호 validation 로직 추가 (정규표현식 이용)
<br/>
#108 이슈에서 작업내용을 확인할 수 있습니다 :)
<br/>
=> [FIX] 가입단계에서 버튼 활성화 로직 고도화

Waving-iOS/Presentation/Signup/ViewController/LoginViewController.swift
- textField delegate 메서드 안 쓰는 것 제거
- password publisher 에서 dropFirst operator 제거 
<br/>
<br/>
=> [FIX] 로그인 패스워드 textField 입력할 때 로그인 버튼 활성화 로직 수정
